### ISSUE TITLE
Add features into motions

### ISSUE THREAD

**Issue by SpandanKumarSahu** [Swarm-IITKgp/SimpleSwarmSimulator#2]
These few features are to be added to the "Motion.h" file
1. Control the velocity of the right and left wheel separately, and hence add the feature of turning about a radius curvature.

2. Smooth the pick-up and declaration and also allow the change of RPM. RPM currently is not being changed.

3.  Allow for a function to stop the bot for a while
stop(int BotID, int time_ms=10)
 if (time_ms>10) time=10;
 usleep(time*1000);
}

**Comment by SpandanKumarSahu** [comment]
@npochhi @theerdha @akshatpandya 
Koushik menoni's handle, anyone?

**Comment by npochhi** [comment]
It's @koushik3.

**Comment by SpandanKumarSahu** [comment]
@theerdha @akshatpandya @koushik3, please look into Nilay's work on the other issue that has been merged, and design these two features, along with forward, backward, right and left turn accordingly.

This won't be much of work, so if anyone decides to take this up, post over here, so that others can try something else. Let's take this as a last work on the simulator until the time demands for improvements! :stuck_out_tongue_winking_eye:

**Comment by akshatpandya** [comment]
I am working on the constants thing to fine tune it and also learning ROS,
and on completing it I'll try gazebo as you said.

So, should I take up this work?

On 21-Mar-2017 6:20 PM, "SpandanKumarSahu" <notifications@github.com> wrote:

@theerdha <https://github.com/theerdha> @akshatpandya
<https://github.com/akshatpandya> @koushik3 <https://github.com/koushik3>,
please look into Nilay's work on the other issue that has been merged, and
design these two features, along with forward, backward, right and left
turn accordingly.

This won't be much of work, so if anyone decides to take this up, post over
here, so that others can try something else. Let's take this as a last work
on the simulator until the time demands for improvements! 😜

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Swarm-IITKgp/SimpleSwarmSimulator/issues/2#issuecomment-288068277>,
or mute the thread

**Comment by SpandanKumarSahu** [comment]
@akshatpandya That would be great! If you don't have much acads load this week, take this up. It's a small task, and I think you can do it in 2-3 hrs.
Also, I will make a git repository for tutorials kind of thing. If you're maintaining a quick and short tutorial for Gazebo, send a PR over it. This will prevent the extra fight that everyone has to take up, when they have to learn and contribute to Swarm.

**Comment by akshatpandya** [comment]
Actually right now I'm learning ROS, once I complete it, I.e. in 1-2 days
I'll take up Gazebo, so I think it would be better if someone else took it.
But if you want me to do it, I'm up for it.

**Comment by SpandanKumarSahu** [comment]
Okay, cool. You focus on Gazebo.

@koushik3 or @theerdha any of you, would you like to take it up?

**Comment by koushik3** [comment]
@SpandanKumarSahu , I'll work on designing the right and left turn

**Comment by theerdha** [comment]
@SpandanKumarSahu I'll work on rpm control

**Comment by npochhi** [comment]
@theerdha RPM would be given as a parameter to the move function. So, in a way, I have introduced the change of RPM.

**Comment by SpandanKumarSahu** [comment]
@koushik3 If you're working with left and right turn, you can additionally write a function that lets the bot turn in with some radius curvature. Also, you can implement forward and backward motion, using the work of Nilay.

**Comment by SpandanKumarSahu** [comment]
@theerdha Yeah, as Nilay said, the change of RPM of the bot can be handled by separately specifying left and right wheel's RPM.

**Comment by theerdha** [comment]
im working on accelerating and decelerating the bot smoothly

**Comment by SpandanKumarSahu** [comment]
@theerdha Great. :)

**Comment by mankeyboy** [comment]
Update this issue, anyone?

**Comment by SpandanKumarSahu** [comment]
@mankeyboy The issue has been redressed. We should have closed this thread much earlier.
