### ISSUE TITLE
Simulator is not closing in the terminal

### ISSUE THREAD

**Issue by npochhi** [Swarm-IITKgp/SimpleSwarmSimulator#5]
I'd added the functionality of closing the Simulator by pressing the ESC key. The output window closes, but the application keeps on running in the terminal.

**Comment by SpandanKumarSahu** [comment]
Yeah, that is because they are running from different threads. When you pressed 'esc', the Output.cpp closed but the algorithms kept running.
Any changes to close/get input from Output.cpp will not affect the running of the algorithms.
One solution is to exit the Simulator.cpp by detecting a key press, but then again, why not directly press ctrl+c on the terminal?

**Comment by npochhi** [comment]
If pressing Ctrl + C is okay for the users, then it's fine for me. :smile: Closing this issue.
